// =============================================================================
// pulse_rom.v
// =============================================================================
// Dual-port ROM storing pre-computed DRAG pulse I/Q samples for four gate types.
//
// Organisation:
//   Gate encoding (3 bits) maps directly to the upper address bits:
//
//     gate_sel | Gate  | Base address (decimal)
//     ---------|-------|----------------------
//     3'b000   | NOP   | 0    (all zeros, no .mem file)
//     3'b001   | X     | 256
//     3'b010   | Y     | 512
//     3'b011   | XH    | 768  (X/2, pi/2 pulse)
//     3'b100   | H     | 1024 (Hadamard approx)
//     3'b101..111      | 1280..1792 (unused, inited to 0)
//
//   ROM address = {gate_sel[2:0], sample_idx[7:0]} = 11-bit
//   Total ROM depth = 2^11 = 2048 (power-of-2 → Vivado infers a single 18k BRAM)
//   Used depth      = 5 * 256 = 1280 entries
//
// Synthesis note:
//   Concatenated address (not multiplication) is required for correct BRAM
//   inference by Xilinx Vivado.  The (*rom_style="block"*) attribute enforces
//   BRAM mapping.  COE files can alternatively be used for production builds.
//
// Ports:
//   clk        - system clock
//   gate_sel   - 3-bit gate selector
//   sample_idx - 8-bit sample index within the selected gate (0..255)
//   load_en    - when high, updates the read address on the next rising edge
//   data_i     - 16-bit signed I sample output (registered, 1-cycle latency)
//   data_q     - 16-bit signed Q sample output
//   valid      - asserted one cycle after load_en
// =============================================================================

`timescale 1ns / 1ps

module pulse_rom #(
    parameter DATA_WIDTH = 16      // bits per I or Q sample (ROM depth is fixed at 2048)
)(
    input  wire                   clk,
    input  wire [2:0]             gate_sel,
    input  wire [7:0]             sample_idx,
    input  wire                   load_en,
    output reg  [DATA_WIDTH-1:0]  data_i,
    output reg  [DATA_WIDTH-1:0]  data_q,
    output reg                    valid
);

    // -------------------------------------------------------------------------
    // ROM storage: depth = 2^(3+8) = 2048 (power-of-2 for BRAM inference)
    // Address = {gate_sel[2:0], sample_idx[7:0]} — no multiplication needed.
    // Upper 768 entries (gate_sel 5/6/7) remain zero.
    // -------------------------------------------------------------------------
    localparam ADDR_BITS   = 3 + 8;            // 11 bits
    localparam TOTAL_DEPTH = 1 << ADDR_BITS;   // 2048

    (* rom_style = "block" *)
    reg signed [DATA_WIDTH-1:0] rom_i [0:TOTAL_DEPTH-1];
    (* rom_style = "block" *)
    reg signed [DATA_WIDTH-1:0] rom_q [0:TOTAL_DEPTH-1];

    // -------------------------------------------------------------------------
    // Initialise ROM from .mem hex files generated by generate_pulse_rom.py.
    // Base addresses match {gate_sel, 8'b0} exactly:
    //   gate 1 (X)  → addr 256  = {3'b001, 8'b0}
    //   gate 2 (Y)  → addr 512  = {3'b010, 8'b0}
    //   gate 3 (XH) → addr 768  = {3'b011, 8'b0}
    //   gate 4 (H)  → addr 1024 = {3'b100, 8'b0}
    // -------------------------------------------------------------------------
    integer k;
    initial begin
        for (k = 0; k < TOTAL_DEPTH; k = k + 1) begin
            rom_i[k] = 0;
            rom_q[k] = 0;
        end
        $readmemh("../mem_files/drag_x_i.mem",  rom_i, 256,  511);
        $readmemh("../mem_files/drag_x_q.mem",  rom_q, 256,  511);
        $readmemh("../mem_files/drag_y_i.mem",  rom_i, 512,  767);
        $readmemh("../mem_files/drag_y_q.mem",  rom_q, 512,  767);
        $readmemh("../mem_files/drag_xh_i.mem", rom_i, 768,  1023);
        $readmemh("../mem_files/drag_xh_q.mem", rom_q, 768,  1023);
        $readmemh("../mem_files/drag_h_i.mem",  rom_i, 1024, 1279);
        $readmemh("../mem_files/drag_h_q.mem",  rom_q, 1024, 1279);
    end

    // -------------------------------------------------------------------------
    // Read logic: address = {gate_sel, sample_idx}  (concatenation, not multiply)
    // This allows Vivado to infer a single 18k BRAM with no DSP usage.
    // -------------------------------------------------------------------------
    wire [ADDR_BITS-1:0] rd_addr = {gate_sel, sample_idx};

    always @(posedge clk) begin
        if (load_en) begin
            valid  <= 1'b0;
        end else begin
            data_i <= rom_i[rd_addr];
            data_q <= rom_q[rd_addr];
            valid  <= 1'b1;
        end
    end

endmodule
